pdf:
	latexmk -pdf -shell-escape presentation.tex

pvc:
	latexmk -pdf -pvc -shell-escape presentation.tex

pdf43:
	latexmk -pdf -shell-escape presentation43.tex

pvc43:
	latexmk -pdf -pvc -shell-escape presentation43.tex

clear:
	latexmk -c
	rm *nav *snm *vrb
	ls -la